# Site settings
title: Nickel's Blog
smalltalk: "Hello, World!"
description: > # My blog Powred by jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "https://kiki912002.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  
facebook_username: 
portfolio_url: 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#highlighter: rouge

# Conversion markdown: redcarpet 
highlighter: pygments 
redcarpet: 
  extensions: 
    ["no_intra_emphasis", 
    "fenced_code_blocks", 
    "autolink", 
    "strikethrough", 
    "superscript"]

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed